# Generated by Django 5.2.7 on 2026-03-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('max_members', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_groups', to='documents.document')),
                ('members', models.ManyToManyField(blank=True, related_name='collaboration_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('note', 'Note'), ('bookmark', 'Bookmark'), ('question', 'Question'), ('correction', 'Correction')], default='highlight', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('highlighted_text', models.TextField(blank=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('position_data', models.JSONField(default=dict)),
                ('color', models.CharField(default='#ffff00', help_text='Hex color code', max_length=7)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='education.collaborationgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('position_data', models.JSONField(default=dict, help_text='Position data for annotation')),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='documents.document')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='education.collaborationgroup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='education.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source_page', models.IntegerField(blank=True, null=True)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(help_text='0-5 rating (0=blackout, 5=perfect)')),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='education.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.IntegerField(default=0)),
                ('pages_completed', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('notes_count', models.IntegerField(default=0)),
                ('flashcards_count', models.IntegerField(default=0)),
                ('study_sessions_count', models.IntegerField(default=0)),
                ('average_flashcard_score', models.FloatField(default=0.0)),
                ('study_streak_days', models.IntegerField(default=0)),
                ('last_study_date', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateTimeField(blank=True, null=True)),
                ('daily_study_goal_minutes', models.IntegerField(default=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('highlighted_text', models.TextField(blank=True, help_text='Highlighted portions from document')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('position_data', models.JSONField(default=dict, help_text='Position data for highlights')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('study_duration', models.IntegerField(help_text='Duration in minutes per session')),
                ('study_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='weekly', max_length=20)),
                ('target_completion', models.DateTimeField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('pages_studied', models.IntegerField(default=0)),
                ('notes_taken', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='documents.document')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='education.studyplanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborationgroup',
            index=models.Index(fields=['document', 'is_public'], name='education_c_documen_474523_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationgroup',
            index=models.Index(fields=['creator'], name='education_c_creator_763565_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['user', 'document'], name='education_a_user_id_c9a633_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['document', 'page_number'], name='education_a_documen_9c7cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['group', 'is_public'], name='education_a_group_i_bfa746_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['group', 'parent'], name='education_d_group_i_5fee13_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['document', 'page_number'], name='education_d_documen_030277_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['user', 'created_at'], name='education_d_user_id_d3a24e_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['user', 'next_review'], name='education_f_user_id_9e2800_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['document', 'difficulty'], name='education_f_documen_050313_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['is_auto_generated'], name='education_f_is_auto_5e18bb_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['user', 'created_at'], name='education_f_user_id_2d2137_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcardreview',
            index=models.Index(fields=['flashcard', 'created_at'], name='education_f_flashca_266d05_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'document'], name='education_l_user_id_ca403f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['user', 'is_completed'], name='education_l_user_id_2234e8_idx'),
        ),
        migrations.AddIndex(
            model_name='learningprogress',
            index=models.Index(fields=['document', 'completion_percentage'], name='education_l_documen_dea466_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'document'], name='education_n_user_id_c4744a_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'is_favorite'], name='education_n_user_id_214e08_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['document', 'is_public'], name='education_n_documen_531b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['tags'], name='education_n_tags_e1b844_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanner',
            index=models.Index(fields=['user', 'start_date'], name='education_s_user_id_8b5cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanner',
            index=models.Index(fields=['user', 'is_completed'], name='education_s_user_id_fa4f93_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplanner',
            index=models.Index(fields=['document', 'user'], name='education_s_documen_56b131_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'start_time'], name='education_s_user_id_5de2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['planner', 'is_completed'], name='education_s_planner_2ebc73_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['document', 'user'], name='education_s_documen_411686_idx'),
        ),
    ]
