# Generated by Django 6.0.6 on 2026-07-15 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('purchase_confirmed', 'Purchase Confirmed'), ('sale_made', 'Sale Made'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('withdrawal_completed', 'Withdrawal Completed'), ('withdrawal_failed', 'Withdrawal Failed'), ('refund_requested', 'Refund Requested on Your Document'), ('refund_processed', 'Refund Processed'), ('review_received', 'Review Received'), ('identity_verified', 'Identity Verified'), ('identity_rejected', 'Identity Rejected'), ('verification_submitted', 'Verification Submitted'), ('wallet_credited', 'Wallet Credited'), ('wallet_debited', 'Wallet Debited'), ('system_message', 'System Message')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_ce6926_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_776dd3_idx')],
            },
        ),
    ]
