# Generated by Django 5.2.7 on 2026-03-15 19:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid by buyer', max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0700'), help_text='Commission rate (7% = 0.0700)', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted for site maintenance', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount credited to seller after commission', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='documents.document')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='documents.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available balance for withdrawal', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings after commission', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission paid to platform', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount withdrawn', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount (positive for credits, negative for debits)', max_digits=12)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Net amount after commission and fees', max_digits=12, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission/fee amount', max_digits=12)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction processing fee', max_digits=12)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Gross sale amount before commission', max_digits=12, null=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale Earnings'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('fee', 'Transaction Fee')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales.sale')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sales.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission deducted (7% for regular users, 0% for superadmin)', max_digits=12)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transaction processing fee', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection', null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='sales.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['seller', 'created_at'], name='sales_sale_seller__95311d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sales_sale_created_e208b3_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='sales_walle_user_id_8f970e_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['created_at'], name='sales_walle_created_a8d321_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'created_at'], name='sales_trans_wallet__3197f3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='sales_trans_transac_71120d_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet', 'status'], name='sales_withd_wallet__b683ab_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='sales_withd_status_a4aa3d_idx'),
        ),
    ]
