# Generated by Django 5.2.7 on 2026-03-15 21:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_wallet_reserved_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Commission deducted on withdrawal (not used; withdrawals are fee-free)', max_digits=12),
        ),
    ]
