# Generated by Django on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_alter_withdrawalrequest_commission"),
        ("withdrawals", "0005_migrate_sales_withdrawals"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WithdrawalRequest",
        ),
    ]

