# Generated by Django 5.2.7 on 2026-03-15 19:50

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('multiple_accounts', 'Multiple Accounts from Same IP'), ('unusual_activity', 'Unusual Activity Pattern'), ('suspicious_uploads', 'Suspicious Upload Behavior'), ('fake_reviews', 'Fake Review Patterns'), ('payment_fraud', 'Payment Fraud Indicators'), ('account_takeover', 'Account Takeover Indicators')], max_length=30)),
                ('risk_score', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('auto_action_taken', models.CharField(choices=[('none', 'None'), ('flagged', 'Flagged for Review'), ('limited', 'Account Limited'), ('suspended', 'Account Suspended')], default='flagged', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_cases', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'risk_score'], name='security_fr_user_id_a14c01_idx'), models.Index(fields=['pattern_type', 'created_at'], name='security_fr_pattern_f2c976_idx'), models.Index(fields=['is_confirmed', 'created_at'], name='security_fr_is_conf_d49637_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('government_id', 'Government ID'), ('student_id', 'Student ID'), ('university_email', 'University Email'), ('phone', 'Phone Number'), ('social', 'Social Media')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verification_data', models.JSONField(default=dict)),
                ('documents', models.JSONField(default=list)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='security_id_user_id_17c7fb_idx'), models.Index(fields=['status', 'created_at'], name='security_id_status_687948_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login Attempt'), ('login_success', 'Successful Login'), ('login_failed', 'Failed Login'), ('password_change', 'Password Change'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled'), ('verification_submitted', 'Identity Verification Submitted'), ('suspicious_activity', 'Suspicious Activity'), ('account_locked', 'Account Locked')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='security_se_user_id_003c3b_idx'), models.Index(fields=['event_type', 'created_at'], name='security_se_event_t_65d091_idx'), models.Index(fields=['severity', 'created_at'], name='security_se_severit_5d499e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default=pyotp.random_base32, max_length=32, unique=True)),
                ('backup_codes', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='security_tw_user_id_cc30f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('watermark_text', models.CharField(blank=True, max_length=100)),
                ('watermark_opacity', models.IntegerField(default=30)),
                ('watermark_position', models.CharField(choices=[('center', 'Center'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='center', max_length=20)),
                ('include_user_info', models.BooleanField(default=True)),
                ('include_timestamp', models.BooleanField(default=True)),
                ('auto_watermark', models.BooleanField(default=True)),
                ('watermark_size', models.IntegerField(default=20)),
                ('watermark_color', models.CharField(default='#CCCCCC', max_length=7)),
                ('watermark_rotation', models.IntegerField(default=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watermark_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='security_wa_user_id_717eac_idx'), models.Index(fields=['auto_watermark'], name='security_wa_auto_wa_95e113_idx')],
            },
        ),
    ]
