# Generated by Django 5.2.7 on 2026-03-15 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2)),
                ('processing_time', models.TimeField(default='12:00')),
                ('is_active', models.BooleanField(default=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('next_processing', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'withdrawal_schedule',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('stripe', 'Stripe Connect'), ('paypal', 'PayPal'), ('bank', 'Direct Bank Transfer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('paypal_verified', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_methods',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payout_type', models.CharField(choices=[('instant', 'Instant Withdrawal'), ('weekly', 'Weekly Payout')], default='weekly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('2fa_required', '2FA Required')], default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('two_fa_verified', models.BooleanField(default=False)),
                ('two_fa_token', models.CharField(blank=True, max_length=10, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='withdrawals.withdrawalmethod')),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('withdrawal_request', 'Withdrawal Request'), ('large_withdrawal', 'Large Withdrawal'), ('failed_withdrawal', 'Failed Withdrawal'), ('suspicious_activity', 'Suspicious Activity'), ('system_alert', 'System Alert'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary')], default='withdrawal_request', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='withdrawals.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_payout_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('withdrawal_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='withdrawals.withdrawalrequest')),
            ],
            options={
                'db_table': 'withdrawal_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='withdrawalmethod',
            index=models.Index(fields=['user', 'is_active'], name='withdrawal__user_id_105611_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalmethod',
            index=models.Index(fields=['method_type', 'is_verified'], name='withdrawal__method__6407c8_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', 'status'], name='withdrawal__user_id_dc11ea_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'requested_at'], name='withdrawal__status_ea6094_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['payout_type', 'requested_at'], name='withdrawal__payout__60f853_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['withdrawal_method', 'status'], name='withdrawal__withdra_d360f6_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type', 'is_read'], name='withdrawals_notific_f37ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['priority', 'created_at'], name='withdrawals_priorit_7082d5_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='withdrawals_created_9b3753_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawaltransaction',
            index=models.Index(fields=['withdrawal_request', 'status'], name='withdrawal__withdra_58dafc_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawaltransaction',
            index=models.Index(fields=['status', 'created_at'], name='withdrawal__status_9b7b57_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawaltransaction',
            index=models.Index(fields=['transaction_id'], name='withdrawal__transac_24cc75_idx'),
        ),
    ]
