# Generated by Django 5.2.7 on 2026-03-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawalrequest_scheduled_for_wallet_debited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='payout_type',
            field=models.CharField(choices=[('weekly', 'Twice Monthly (14th & 28th)')], default='weekly', max_length=20),
        ),
    ]
