# Generated by Django 6.0.6 on 2026-07-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0005_migrate_sales_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='requires_email',
            field=models.BooleanField(default=False),
        ),
    ]
