# Generated by Django 5.2.7 on 2026-03-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category_type', models.CharField(choices=[('course', 'Course Materials'), ('subject', 'Subject Specific'), ('notes', 'Class Notes'), ('revision', 'Revision Papers'), ('exam', 'Exam Papers'), ('guide', 'Study Guides'), ('reference', 'Reference Materials'), ('lab', 'Lab Reports'), ('project', 'Project Reports'), ('thesis', 'Thesis & Dissertations'), ('case_study', 'Case Studies'), ('tutorial', 'Tutorials'), ('syllabus', 'Syllabus'), ('textbook', 'Textbooks'), ('assignment', 'Assignments'), ('research', 'Research Papers'), ('presentation', 'Presentations'), ('worksheet', 'Worksheets'), ('cheat_sheet', 'Cheat Sheets'), ('other', 'Other')], default='other', help_text='Type of category for better organization', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this category contains', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class for category display (e.g., bi-book, bi-file-text, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is available for new uploads')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'category_type', 'name'],
                'indexes': [models.Index(fields=['category_type', 'name'], name='documents_c_categor_59165c_idx'), models.Index(fields=['is_active', 'sort_order'], name='documents_c_is_acti_4902fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('preview_text', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('notes', 'Class Notes'), ('revision', 'Revision Papers'), ('exam', 'Exam Papers'), ('guide', 'Study Guide'), ('textbook', 'Textbook Chapter'), ('assignment', 'Assignment Solution'), ('research', 'Research Paper'), ('presentation', 'Presentation'), ('lab', 'Lab Report'), ('project', 'Project Report'), ('thesis', 'Thesis'), ('case_study', 'Case Study'), ('tutorial', 'Tutorial'), ('syllabus', 'Syllabus'), ('worksheet', 'Worksheet'), ('cheat_sheet', 'Cheat Sheet'), ('other', 'Other')], default='other', help_text='Type of document for better searchability', max_length=20)),
                ('academic_level', models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('professional', 'Professional'), ('other', 'Other')], default='other', help_text='Academic level this document is suitable for', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject area (e.g., Mathematics, Biology, History)', max_length=100)),
                ('course_code', models.CharField(blank=True, help_text='Course code (e.g., MATH101, BIO202)', max_length=20)),
                ('isbn', models.CharField(blank=True, help_text='ISBN for textbooks or reference materials', max_length=20)),
                ('author', models.CharField(blank=True, help_text='Author or professor name', max_length=100)),
                ('university', models.CharField(blank=True, help_text='University or institution', max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Academic year or publication year', null=True)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags for better searchability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (Card)'), ('paypal', 'PayPal'), ('bank', 'Direct Bank Transfer')], default='stripe', max_length=20)),
                ('currency', models.CharField(choices=[('usd', 'USD ($)'), ('eur', 'EUR (€)'), ('gbp', 'GBP (£)')], default='usd', max_length=10)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['seller', 'created_at'], name='documents_d_seller__bb8ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', 'created_at'], name='documents_d_categor_f827e2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['price'], name='documents_d_price_918ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'academic_level'], name='documents_d_documen_2d8326_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['subject', 'course_code'], name='documents_d_subject_2aba87_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tags'], name='documents_d_tags_41a05e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_d_title_ccf306_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='documents_o_buyer_i_d07752_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['document', 'status'], name='documents_o_documen_028384_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='documents_o_created_0c2672_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='documents_o_status_14fdff_idx'),
        ),
    ]
