# Generated by Django 5.2.7 on 2026-03-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_refundrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='documents_r_status_ad38e7_idx',
            old_name='documents_re_status_0e2e84_idx',
        ),
        migrations.RenameIndex(
            model_name='refundrequest',
            new_name='documents_r_buyer_i_685453_idx',
            old_name='documents_re_buyer_i_8b2c1b_idx',
        ),
    ]
